<!--
(APENAS LEIA)

finally
Usando depois do catch.
    try{}
    catch(Exception1 e){}
    catch(Exception2 e){}
    finally{}

Geralmente é usado para fechar objetos.
Ex:
Fechar o objeto da classe Scanner.
    finally{
        objetctName.close();
    }


O finally é executado em qualquer situacao. Se não acontecer o erro, o finally aparece.
E se acontecer o erro, o finally também aparece.

Geralmente é usado para fechar objetos.

-->